import { MikroORM } from '@mikro-orm/postgresql';
import { collectIoTables, IoTable } from './tableRegistry.js';
import { pgDumpData, psqlScript, readPgCredentials } from './pgClient.js';

const STAGING_SCHEMA = 'io_staging';

export type ImportReportRow = {
    table_name: string;
    inserted: number;
    updated: number;
};

export type ExportResult = {
    filename: string;
    sql: string;
};

function quote(identifier: string): string {
    return `"${identifier.replace(/"/g, '""')}"`;
}

export async function exportDatabase(orm: MikroORM): Promise<ExportResult> {
    const credentials = readPgCredentials();
    const tables = collectIoTables(orm);

    // pg_dump exporte tout le schéma public : on lui retire nommément ce que le registre ne
    // couvre pas, plutôt que de lister ce qu'il doit prendre. Une table présente en base mais
    // sans entité (relique de migration) sortirait sinon du dump sans qu'on le remarque.
    const known = new Set(tables.map(table => table.tableName));
    const excluded = await tablesNotIn(orm, known);

    const sql = await pgDumpData(credentials, excluded);

    const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    return { filename: `${credentials.database}-${stamp}.sql`, sql };
}

async function tablesNotIn(orm: MikroORM, known: Set<string>): Promise<string[]> {
    const rows = await orm.em
        .getConnection()
        .execute<{ tablename: string }[]>(`SELECT tablename FROM pg_tables WHERE schemaname = 'public'`);

    return rows.map(row => row.tablename).filter(name => !known.has(name));
}

export type ImportOptions = {
    /** Joue l'import et lit son rapport, puis annule tout : la base ressort inchangée. */
    dryRun?: boolean;
};

export async function importDatabase(
    orm: MikroORM,
    dump: string,
    options: ImportOptions = {},
): Promise<ImportReportRow[]> {
    const credentials = readPgCredentials();
    const tables = collectIoTables(orm);

    const script = buildImportScript(tables, dump, options.dryRun ?? false);
    const output = await psqlScript(credentials, script);

    return parseReport(output);
}

// Exportées pour les tests : ce sont les seules pièces de l'import qui se vérifient sans base,
// et redirectToStaging est celle dont une erreur passe le plus inaperçue.
export function buildImportScript(tables: IoTable[], dump: string, dryRun = false): string {
    const byName = new Map(tables.map(table => [table.tableName, table]));
    const staged = redirectToStaging(dump, byName);

    const createStaging = [
        `DROP SCHEMA IF EXISTS ${quote(STAGING_SCHEMA)} CASCADE;`,
        `CREATE SCHEMA ${quote(STAGING_SCHEMA)};`,
        `CREATE TABLE ${quote(STAGING_SCHEMA)}._report (table_name text, inserted bigint, updated bigint);`,
        ...tables.map(
            table =>
                `CREATE TABLE ${quote(STAGING_SCHEMA)}.${quote(table.tableName)} ` +
                `(LIKE public.${quote(table.tableName)} INCLUDING DEFAULTS);`,
        ),
    ].join('\n');

    const upserts = tables.map(buildUpsert).join('\n\n');

    return [
        '-- Generated by ioPort import. Runs as a single transaction.',
        createStaging,
        '',
        '-- === dump payload (redirected to the staging schema) ===',
        staged,
        '-- === end of dump payload ===',
        '',
        upserts,
        '',
        `SELECT COALESCE(json_agg(row_to_json(r))::text, '[]') FROM ${quote(STAGING_SCHEMA)}._report r;`,
        // psql tourne en --single-transaction : le rapport est déjà lu à ce point, donc annuler
        // rend la base à son état d'avant sans rien retirer à ce qu'on a appris. Le schéma de
        // transit disparaît avec la transaction, d'où l'absence de DROP dans cette branche.
        dryRun ? 'ROLLBACK;' : `DROP SCHEMA ${quote(STAGING_SCHEMA)} CASCADE;`,
    ].join('\n');
}

// `xmax = 0` est vrai pour une ligne réellement insérée et faux pour une ligne qui a suivi la
// branche DO UPDATE : c'est ce qui permet de distinguer les deux sans relire la table.
export function buildUpsert(table: IoTable): string {
    const columns = table.columns.map(quote).join(', ');
    const conflict = table.primaryKeys.map(quote).join(', ');
    const updatable = table.columns.filter(column => !table.primaryKeys.includes(column));

    const onConflict =
        updatable.length === 0
            ? 'DO NOTHING'
            : `DO UPDATE SET ${updatable.map(c => `${quote(c)} = EXCLUDED.${quote(c)}`).join(', ')}`;

    return [
        `WITH upserted AS (`,
        `    INSERT INTO public.${quote(table.tableName)} (${columns})`,
        `    SELECT ${columns} FROM ${quote(STAGING_SCHEMA)}.${quote(table.tableName)}`,
        `    ON CONFLICT (${conflict}) ${onConflict}`,
        `    RETURNING (xmax = 0) AS was_inserted`,
        `)`,
        `INSERT INTO ${quote(STAGING_SCHEMA)}._report (table_name, inserted, updated)`,
        `SELECT '${table.tableName}',`,
        `       count(*) FILTER (WHERE was_inserted),`,
        `       count(*) FILTER (WHERE NOT was_inserted)`,
        `FROM upserted;`,
    ].join('\n');
}

const COPY_HEADER = /^COPY\s+(?:public|"public")\.("?)([^"\s(]+)\1\s*\(/;
const INSERT_HEADER = /^INSERT INTO\s+(?:public|"public")\.("?)([^"\s(]+)\1\s*[\s(]/;

// Le corps d'un COPY est du TSV brut : une ligne de données peut parfaitement commencer par le
// mot COPY. On ne peut donc pas remplacer à l'aveugle dans tout le fichier — il faut savoir si
// on se trouve dans un bloc de données ou dans du SQL, d'où ce passage ligne à ligne.
export function redirectToStaging(dump: string, tables: Map<string, IoTable>): string {
    const lines = dump.split('\n');
    const output: string[] = [];
    let inCopyBlock = false;

    for (const line of lines) {
        if (inCopyBlock) {
            // Le terminateur de COPY est une ligne contenant exactement `\.`
            if (line.trimEnd() === '\\.') inCopyBlock = false;
            output.push(line);
            continue;
        }

        const match = COPY_HEADER.exec(line) ?? INSERT_HEADER.exec(line);
        if (!match) {
            output.push(line);
            continue;
        }

        const tableName = match[2];
        if (!tables.has(tableName)) {
            // Laisser passer la ligne la ferait écrire directement dans public, sans le
            // ON CONFLICT : ce serait un import brut déguisé en upsert.
            throw new Error(`Dump contains table "${tableName}", which has no matching entity — refusing to import it`);
        }

        output.push(line.replace(/^(COPY|INSERT INTO)\s+(?:public|"public")\./, `$1 ${quote(STAGING_SCHEMA)}.`));
        if (COPY_HEADER.test(line) && /FROM stdin;\s*$/.test(line)) inCopyBlock = true;
    }

    return output.join('\n');
}

export function parseReport(output: string): ImportReportRow[] {
    const lines = output
        .split('\n')
        .map(line => line.trim())
        .filter(Boolean);

    for (let i = lines.length - 1; i >= 0; i--) {
        if (!lines[i].startsWith('[')) continue;
        try {
            return JSON.parse(lines[i]) as ImportReportRow[];
        } catch {
            break;
        }
    }

    return [];
}
