export { AuthProvider, useAuth, type AuthUser } from './auth/AuthContext'
export { ProtectedRoute } from './auth/ProtectedRoute'
export { ThemeProvider, useTheme } from './theme/ThemeContext'
export { themes, type Theme } from './theme/themes'
export { NavBar, type NavLink } from './components/NavBar'
export { Button, type ButtonVariant } from './components/Button'
export { ColorPicker } from './components/ColorPicker'
export { PopupProvider } from './popup/PopupProvider'
