export { AuthProvider, useAuth, type AuthUser } from './auth/AuthContext'
export { ProtectedRoute } from './auth/ProtectedRoute'
export { PopupProvider } from './popup/PopupProvider'
export { popupMessages } from './popup/messages'

export {
  Modal,
  openModal,
  closeModal,
  ColorPicker,
  ColorField,
  ConfirmDeleteButton,
  Button,
  NavBar,
  PageMessage,
  LoadingMessage,
  ErrorMessage,
  ThemeProvider,
  useTheme,
  ThemeSelect,
  defaultPalette,
  themeVariableGroups,
  themeVariableKeys,
  createLocalThemeStore,
  createHttpThemeStore,
  serializeColors,
  parseColors,
  isHexColor,
  randomHex,
  fetchJson,
  useDocumentTitle,
  useAsync,
  useElementSize,
  useClickOutside,
  useEscapeKey,
  type ButtonVariant,
  type NavLink,
  type LoadStatus,
  type AsyncStatus,
  type AsyncResult,
  type ElementSize,
  type ThemeColors,
  type ThemeDefinition,
  type ThemeCatalog,
  type ThemeDraft,
  type ThemeStore,
  type ThemeVariableGroup,
  type PopupMessages,
} from '@-reddacted-/react-ui'
